import './globals.css'
import type { Metadata } from 'next'
import { Mochiy_Pop_One_normal } from '@/app/fonts'
import 'ress'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ja' className={Mochiy_Pop_One_normal.className}>
      <body>{children}</body>
    </html>
  )
}
